--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AlexPads/KitsPlus
branches:
- master
projects:
  KitsPlus:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
