name: KitsPlus
description: Simple Chest Kits with Fully customizeable Everything!
main: WitherHosting\ChestKits\Main
author: WitherHosting / (AlexPads)
version: 1.0.7
api: 3.0.0
depend:
  - EconomyAPI
  - PurePerms
softdepend:
  - PiggyCustomEnchants
commands:
  kit:
    description: "List kits or Gives GUI"
  kitgive:
    description: "Give a Player a Kit"
    permission: kp.kitgive
  kitlist:
    description: "Shows console users what kits are available"