name: KitsG
description: Simple Chest Kits with Fully customizeable Everything!
main: SaltyPixelDevz\ChestKits\Main
author: SaltyPixelDevz / (AlexPads)
version: 1.0.1
api: [3.0.0]

commands:
  gkit:
    description: "Claim a GKit"
