name: KitsPlus
description: Simple Chest Kits with Fully customizeable Everything!
main: SaltyPixelDevz\ChestKits\Main
author: SaltyPixelDevz / (AlexPads)
version: 1.0
api: [3.0.0]

commands:
  kit:
    description: "List kits or Gives GUI"